### ISSUE TITLE
Periodicidade da coleta dos dados

### ISSUE THREAD

**Issue by Dayof** [unb-cic-esw/youtube-data-monitor#22]
EU : pesquisador(a)
QUERO : coletar as informações de cada canal de cada um dos 67 atores às 12pm todos os dias
PARA : avaliar o nível de engajamento de cada ator nas mídias sociais.

Testes de aceitação:
- Gerar resultados em um arquivo no formato CSV na pasta com a data e hora da coleta, e.g.:
  - 2018-23-04_15:12
    - canais.csv
    - ujs_brasil.csv
    - uneoficial.csv
    - midia_ninja.csv
- Nos resultados conter as seguintes informações:
  - Título do ator;
  - ID e/ou username do canal do ator;
  - Quantidade de visualizações por canal;
  - Quantidade de inscritos por canal; 
  - Quantidade de vídeos por canal;
  - Quantidade de visualizações de cada vídeo do canal;

**Comment by alegomes** [comment]
> (...) coletar as informações de cada canal (...)
Será que não vale a pena especificar já aqui na estória quais infos são essas para não correr o risco de termos a mesma estória repetida em várias sprints?

> 2018-23-04_15:12
1. Por que essa mistureba de símbolos ( - , _ , : )?
2. Por que não apenas 201804231512?
3. Este timestamp está incluso em uma coluna no CSV? Acho interessante, pra facilitar a importação.

[]s

**Comment by Dayof** [comment]
> Será que não vale a pena especificar já aqui na estória quais infos são essas para não correr o risco de termos a mesma estória repetida em várias sprints?

Acho que não iremos repetir porque esta é especificamente sobre dados coletados às 12pm, se tiver outras estórias para mais coletas de dados aí não iríamos mais especificar sobre a periodicidade da coleta.

> Por que essa mistureba de símbolos ( - , _ , : )? 

O datetime do python já gera um "2018-23-04 15:12", iremos adicionar apenas um underline para não conter pastas com espaços.

> Por que não apenas 201804231512?

Não é legível. Acredito que maior legibilidade seja nosso objetivo.

> Este timestamp está incluso em uma coluna no CSV? Acho interessante, pra facilitar a importação.

Não,  seria redundante. Colocamos em pastas ou em colunas, se preferir colunas aí retiro a estrutura por pastas. Posteriormente iremos deixar tudo em banco de dados em vez de CSV. A ideia de servir CSV agora é puramente para entregar valor da forma mais simples.
