### ISSUE TITLE
Coleta mais detalhada de cada vídeo dos canais dos atores

### ISSUE THREAD

**Issue by Dayof** [unb-cic-esw/youtube-data-monitor#23]
EU : pesquisador(a)
QUERO : coletar mais dados (número de ```likes```, número de ```dislikes```, número de comentários, número de pessoas que favoritaram o vídeo, quantidade de comentários do canal, categoria dos vídeos, link para os vídeos) dos vídeos de cada um dos 67 atores
PARA : avaliar o nível de engajamento de cada ator nas mídias sociais.

Testes de aceitação:    
- Gerar resultados em um arquivo no formato CSV com a data e hora da coleta;    
- Nos resultados conter as seguintes informações dos vídeos dos 67 atores:
  - número de ```likes```;
  - número de ```dislikes```;
  - número de comentários;
  - número de pessoas que favoritaram o vídeo;
  - quantidade de comentários do canal;
  - categoria dos vídeos;
  - link para os vídeos.

**Comment by alegomes** [comment]
Boa. Para não haver disse-me-disse, acho que poderia especificar as colunas do CSV nos critérios de aceitação.

**Comment by Dayof** [comment]
> Para não haver disse-me-disse, acho que poderia especificar as colunas do CSV nos critérios de aceitação.

Ajeitado!

**Comment by RafaelChianca** [comment]
Não foi possível adicionar a categoria dos vídeos no arquivo CSV, já que um vídeo pode se encaixar em muitas categorias e, com isso, a API retorna uma lista. Além disso, o número de comentários total do canal não é possível de obter por meio da API pois a mesma apenas retorna o número de comentários de uma sessão específica dos canais chamada "discussão" que nem todos canais possuem, e mesmo os que possuem a contagem fica errada em relação ao que aparece quando visitamos os canais específicos. Nossa suspeita é de que os comentários excluídos pelos donos dos canais não são removidos da contagem. Apesar dessa peculiaridade da API, essa funcionalidade foi implementada do mesmo jeito.
