### ISSUE TITLE
Integração com módulo de visualização de dados

### ISSUE THREAD

**Issue by Dayof** [unb-cic-esw/youtube-data-monitor#24]
EU : desenvolvedor(a)
QUERO : servir todos os dados coletados pelo youtube-data-monitor para o módulo de visualização de dados 
PARA : mostrar os dados coletados para o cliente de forma unificada.

Testes de aceitação:
- Ter um dyno no heroku executando o youtube-data-monitor;
- Listar todos os atores disponíveis para consulta com o endpoint ```https://youtube-data-monitor.herokuapp.com/actors ```. E.g GET ```https://youtube-data-monitor.herokuapp.com/actors/ ```, response JSON:

``` json
{ 
  "actors" : [
    "une_-_união_nacional_dos_estudantes",
    "marina_silva"
  ]
}
``` 

- Listar datas de coleta do sistema com o endpoint ```https://youtube-data-monitor.herokuapp.com/dates```. E.g GET ```https://youtube-data-monitor.herokuapp.com/dates ```, response JSON:

``` json
{ 
  "dates" : [
    "06-05-2018",
    "07-05-2018",
  ]
}
``` 

- Acessar o endpoint ```https://youtube-data-monitor.herokuapp.com/<data>/canal/<ator>/ ``` para coletar informações (título do canal, username do canal, ID do canal, quantidade de vídeos, quantidade de visualizações e número de inscritos) do canal de um ```<ator>``` coletados na ```<data>``` definida. E.g. GET ```https://youtube-data-monitor.herokuapp.com/07-05-2018/canal/UNE_-_União_Nacional_dos_Estudantes```, response JSON : 

``` json
{ 
  "actor" : "UNE - União Nacional dos Estudantes", 
  "username" : "uneoficial", 
  "channel_id" : "UCI9UhLCYUB8v82jdVvJMnuA", 
  "video_count" : "427", 
  "view_count" : "315299", 
  "subscribers" : "2905" 
}
``` 

- Acessar o endpoint ```https://youtube-data-monitor.herokuapp.com/<data>/canal/<ator>/videos ``` para coletar informações dos vídeos (título dos vídeos e quantidade de vizualizações de cada vídeo) do canal de um ```<ator>``` coletados na ```<data>``` definida. E.g. GET ```https://youtube-data-monitor.herokuapp.com/07-05-2018/canal/marina_silva/videos```, response JSON : 

``` json
{ 
  "videos" : [
    {
      "title" : "Temer, Aécio, Renan e cia também precisam ser punidos", 
      "views" : "456" 
    }, 
    { 
      "title" : "Se a escola for boa pra todo mundo, a gente muda a realidade do Brasil", 
      "views" : "351" 
    }, 
    { 
      "title" : "Não vale tudo para ganhar uma eleição", 
      "views" : "331" 
    }
  ] 
}
``` 

- Caso não haja dado coletado na ```<data>``` passada na url,  o GET irá retornar erro 450. E.g. : GET ```https://youtube-data-monitor.herokuapp.com/2020-23-04/canal/marina_silva``` ou ```https://youtube-data-monitor.herokuapp.com/2020-23-04/canal/marina_silva/videos```, response JSON : 

``` json
{
  "message": "Date was mistyped or our database didn't collected data in this date. Try a date in this format day-month-year, e.g. 07-05-2018."
}

``` 

- Caso o nome do ator ```<actor>``` passado na url for digitado errado ou não existir em nosso banco de dados,  o GET irá retornar erro 460. E.g. : GET ```https://youtube-data-monitor.herokuapp.com/07-05-2018/canal/marina``` ou ```https://youtube-data-monitor.herokuapp.com/07-05-2018/canal/marina/videos```, response JSON : 

``` json
{
  "message":  "Actor name was mistyped or this actor name don't exist in our database. Try list all the actors in youtube-data-monitor.herokuapp.com/actors."
}

``` 

- Coletar últimos dados dos vídeos com ```https://youtube-data-monitor.herokuapp.com/latest/canal/<ator>/videos ```  ou dos canais com ```https://youtube-data-monitor.herokuapp.com/latest/canal/<ator> ```.

- Observações:
  - Substituir espaços em branco por ```_``` no título dos atores. Título do ator pode conter caracteres capitalizados ou não, e.g. ```UJS_Brasil``` ou ```ujs_brasil``` irá acessar os mesmos dados.
  - Todos os dias o youtube-data-monitor atualiza os dados de coleta meia-noite

**Comment by alegomes** [comment]
> QUERO : servir todos os dados do youtube-data-monitor (...)

"servir todos os dados **coletados** pelo youtube-data-monitor (...)" ?

> Ter um dyno no heroku (...)

Isso é relevante pro cliente?

> Acessar o endpoint https://youtube-data-monitor.herokuapp.com/canal/<ator>

O `username` não é menos ambíguo?

> Com este POST acima os dados visualizados nos endpoints https://youtube-data-monitor.herokuapp.com/canal/<ator> e https://youtube-data-monitor.herokuapp.com/canal/<ator>/videos serão alterados para mostrar dados coletados na data de 23 de Abril de 2018. 

Por que não informar a data como parâmetro da requisição? REST é stateless.

> Acessar o endpoint https://youtube-data-monitor.herokuapp.com/canal/<ator>/videos para ver informações ~a certa~ dos vídeos do canal 

acerca

> Caso não aja dado coletado (...)

haja :-)

[]s

**Comment by mikaelmello** [comment]
Talvez um endereço como `host/<data>/canal/<ator>/` fosse melhor, pois tendo `<data>` como primeiro parâmetro para todos os grupos ia facilitar nossa automatização aqui

**Comment by Dayof** [comment]
Para as respostas do @alegomes : 

> "servir todos os dados coletados pelo youtube-data-monitor (...)" ?

Corrigido!

> Isso é relevante pro cliente?

No caso coloquei como cliente o desenvolvedor, talvez nessa perspectiva não seria interessante?

> O username não é menos ambíguo?

Nem todos os atores tem username, mas todos tem um channel_id e o nome que vocês deram para eles.

> Por que não informar a data como parâmetro da requisição? REST é stateless.

Pode ser também, já que você o @mikaelmello do dataviz preferem então vou alterar ! 

> Correções gramaticais 

 Corrigidos !

**Comment by Dayof** [comment]
Sobre respostas do @mikaelmello : 

> Talvez um endereço como host/<data>/canal/<ator>/ fosse melhor, pois tendo <data> como primeiro parâmetro para todos os grupos ia facilitar nossa automatização aqui

Ok!

> Outro detalhe, tem como listar todos os atores cadastrados?

Não, posso definir isso também !

**Comment by Dayof** [comment]
Critérios de aceitação aceitos na data de 10/05/2018.

Urls:
- https://youtube-data-monitor.herokuapp.com/actors
- https://youtube-data-monitor.herokuapp.com/dates
- https://youtube-data-monitor.herokuapp.com/< data >/canal/< ator >
- https://youtube-data-monitor.herokuapp.com/< data >/canal/< ator >/videos
