### ISSUE TITLE
Refatorar branch dev-VideoViewCount

### ISSUE THREAD

**Issue by Adamacenog** [unb-cic-esw/youtube-data-monitor#27]
EU : desenvolvedor(a)
QUERO :  -Retirar as funções de username desnecessárias, evitando redundância;
                - Retirar a redundância de funções;
                 -Criar as colunas em PORTUGUÊS;
                 -Separar a forma de consulta de vídeos e forma de consulta de informações do canal (criando, talvez, novos módulos e classes);
PARA : -uma melhor manutenibilidade do projeto.

Teste de aceitação:
-Não ter mais funções com username 
-Não ter redundâncias de funções
-O CSV gerado ter suas colunas em português
-Ter uma nova classe com as funções do VideoViewCount separada da youtube.py
-Passar com sucesso no build

**Comment by Dayof** [comment]
@Adamacenog podemos fechar esta issue?
