### ISSUE TITLE
Endpoint /dates retorna datas no formato inválido

### ISSUE THREAD

**Issue by mikaelmello** [unb-cic-esw/youtube-data-monitor#50]
As datas são retornadas neste formato, mas para acessar os dados vocês só aceitam `07-05-2018`, desse modo não podemos simplesmente iterar sobre as datas possíveis.

```
{
  dates: [
    "07-05-2018_00:00:01",
    "06-05-2018_00:00:01"
  ]
}
```

**Comment by mikaelmello** [comment]
Aliás, é possível que as datas sejam retornadas em formato Date?

**Comment by joao96** [comment]
To dando uma olhada nesses dates. Mas acredito que o 06-05-2018 funcione sim.
Além disso, estou adicionando as outras coletas

**Comment by mikaelmello** [comment]
@joao96 o que não funciona é acessar pelo formato que vocês manda, o `06-05-2018_00:00:01` inteiro, a gente tá tendo que retirar do underline pra frente

**Comment by joao96** [comment]
Entendi, vou mudar aqui. Aí te aviso.

**Comment by mikaelmello** [comment]
```
Bancada Ativista
2018-05-20
{ date: 2018-05-20T00:00:00.000Z,
  subscribers: '',
  videos: '',
  views: '' }
Bancada Ativista
2018-05-21
{ date: 2018-05-21T00:00:00.000Z,
  subscribers: 'null',
  videos: 'null',
  views: 'null' }
```

O padrão para indicar que não teve coleta vai ser `null` ou string vazia? Seria daora se vocês retornassem um código de erro tipo 404 ao invés de código 200

**Comment by joao96** [comment]
To modificando umas coisas aqui, rapidão.

**Comment by joao96** [comment]
O que você acha dessa mensagem:
{
message: "Actor name was mistyped or this actor name don't exist in our database. Try list all the actors at youtube-data-monitor.herokuapp.com/actors."
}
Retorna um código 460.

**Comment by joao96** [comment]
Para quando não há nenhuma coleta do ator.

**Comment by mikaelmello** [comment]
Sim, tudo certo

Em ter, 22 de mai de 2018 às 15:32, João Victor de Souza Poletti <
notifications@github.com> escreveu:
