### ISSUE TITLE
Retornar URL do canal na API

### ISSUE THREAD

**Issue by mikaelmello** [unb-cic-esw/youtube-data-monitor#51]
Seria útil se retornassem a URL do canal na API.

**Comment by joao96** [comment]
Nas coletas mais recentes, esse dado está presente nos dados de cada canal

**Comment by mikaelmello** [comment]
Daora, não sabia, outra pergunta, tem algumas coletas que todos os campos são null mas mesmo assim o request retorna código 200.

Note que isso é só para algumas

**Comment by mikaelmello** [comment]
https://youtube-data-monitor.herokuapp.com/08-05-2018/canal/Cristovam%20Buarque

**Comment by joao96** [comment]
Entendi. Acredito que isso tenha sido um problema da coleta no dia mesmo. A coleta pode ter sido interrompida e acabamos dando deploy achando que tinha sido completada.

De qualquer forma, se vocês estiverem problema com isso nas próximas coletas, nos avise que averiguamos melhor.
