### ISSUE TITLE
Requisito funcional : Canais 

### ISSUE THREAD

**Issue by Dayof** [unb-cic-esw/youtube-data-monitor#8]
EU : pesquisador(a)
QUERO : saber se os 75 atores possuem ou não canais cadastrados no YouTube
PARA : avaliar o nível de engajamento de cada ator nas mídias sociais

- Testes de aceitação:
  - Gerar resultados em um arquivo no formato CSV
  - Nos resultados conter ator e link do canal 
  - Caso não encontrar canal de um certo ator mostrar que dado do ator é ausente

**Comment by patrickvrb** [comment]
Abaixo estão os resultados dos critérios de aceitacão:
- [ACEITO] Os arquivos CSV estão sendo gerados com nome de ```youtube.csv``` dentro da pasta data
- [ACEITO] Nos resultados estão contidos ator, username e channel_id
- [ACEITO] Dados ausentes estão demonstrados como strings vazias
