### ISSUE TITLE
Requisito funcional : Visualizações dos canais

### ISSUE THREAD

**Issue by Dayof** [unb-cic-esw/youtube-data-monitor#9]
EU : pesquisador(a)
QUERO : coletar a quantidade geral de visualizações dos canais de cada ator
PARA : avaliar o nível de engajamento de cada ator nas mídias sociais

- Testes de aceitação:
  - Gerar resultados em um arquivo no formato CSV
  - Nos resultados conter a quantidade de visualizações dos canais dos 75 atores a partir período de Janeiro de 2018
  - Caso não encontrar canal de um certo ator mostrar que dado do ator é ausente

**Comment by lucascamposj** [comment]
O seguinte teste de aceitação não foi possível realizar utilizando as APIs do Youtube devido a limitações da plataforma com autorizações para tipo de dado requisitado, histórico de informações sobre um canal.

Teste de aceitação: Nos resultados conter a quantidade de vizualizações dos canais dos 75 atores a partir período de Janeiro de 2018.

A pesquisa entorno de soluções para o requisito envolveu utilizar Analytics and Reporting APIs, porém as mesmas possuem a seguinte condição que impossibilita a coleta dos dados da forma atual, sem a autorização dos donos dos canais:

> All YouTube Analytics and YouTube Reporting API requests must be authorized by the channel or content owner that owns the requested data.

Link da documentação das APIs: [https://developers.google.com/youtube/reporting/](url)

Entretanto, é possível coletar a quantidade atual de vizualizações do canal com a YouTube Data API. Logo, com a coleta periódica dos dados é possível gerar um base de dados própria com as informações.
Sendo assim a solução alternativa, será adicionado a data do momento da coleta nos resultados.

**Comment by RafaelChianca** [comment]
Critérios de aceitação propostos:
-  [ACEITO] Os arquivos CSV estão sendo gerados com nome de youtube.csv dentro da pasta data.
-  [ACEITO] Não foi possível obter histórico dos canais desde Janeiro de 2018 devido os termos de uso da API do YouTube. Apesar disso, foi entregue o número de vizualizações dos canais no momento da coleta.
-  [ACEITO] Dados ausentes estão demonstrados como strings vazias.
